name: Audiobookshelf
version: 1.1.2
slug: audiobookshelf
description: Self-hosted audiobook and podcast server
url: https://github.com/helix-git/haos-abs
arch:
  - aarch64
  - amd64
image: ghcr.io/helix-git/haos-abs/{arch}
init: false
ingress: true
ingress_port: 13378
ingress_stream: true
panel_icon: mdi:book-music
panel_title: Audiobookshelf
ports:
  13378/tcp: null
ports_description:
  13378/tcp: Audiobookshelf (for mobile apps, optional)
map:
  - config:rw
  - media:rw
  - share:rw
apparmor: false
options:
  metadata_path: /share/audiobookshelf/metadata
schema:
  metadata_path: str
startup: application
